name: main
run-name: ${{ github.actor }} is running the pipelin on main
on:
  push:
    branches:
      - "main"
      - "demo-1-video-recording"
  
env:
  LATEST_TAG: cypher4859/cowabunga-pizza:latest

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout our code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.LATEST_TAG }}